---
- hosts: web_servers
  become: true
  tasks:
    - name: Update apt-get(yum in centos) repository
      apt:
        update_cache: yes

    - name: Install nginx
      apt:
        name: "nginx"
        state: present

    - name: Createfolder for website
      file:
        path: "/var/www/{{ website_name }}"
        state: directory

    - name: Delete sites-enable and sites-available files
      file:
        path: "{{ item }}"
        state: absent
      with_items:
        - "/etc/nginx/sites-enabled/default"
        - "/etc/nginx/sites-available/default"
      notify:
        - Restart nginx

    - name: Add webpage to servers
      template:
        src: "index.html.tpl"
        dest: "/var/www/{{ website_name }}/index.html"

    - name: Configure nginx with new config file
      template:
        src: "default.tpl"
        dest: "/etc/nginx/sites-available/{{ website_name }}"

    - name: Create symlink for config file
      file:
        src: "/etc/nginx/sites-available/{{ website_name }}"
        dest: "/etc/nginx/sites-enabled/{{ website_name }}"
        state: link
      notify:
        - Restart nginx

  handlers:
    - name: Restart ngninx service
      service:
        name: "nginx"
        state: restarted